'use strict';
const $=id=>document.getElementById(id),SHARKS=window.SHARKS,KEY='sharkline-v2-save',statuses={EN:'En danger',VU:'Vulnérable',NT:'Quasi menacé',CR:'En danger critique',LC:'Préoccupation mineure',EX:'Espèce éteinte'};
const zones=[{id:'reef',name:'Récif lumineux',icon:'≋',description:'Eaux claires · Première exploration'},{id:'wreck',name:'Épave oubliée',icon:'⚓',description:'Filets et vestiges · Reste agile'},{id:'abyss',name:'Les abysses',icon:'◌',description:'Faible lumière · Garde tes repères'}];
let save={coins:150,owned:['reef'],selected:'reef',best:0,runs:[],version:2},memoryOnly=false;
function validSave(v){if(!v||v.version!==2||!Number.isSafeInteger(v.coins)||v.coins<0||!Array.isArray(v.owned))throw Error('Sauvegarde invalide');return{version:2,coins:v.coins,owned:[...new Set(['reef',...v.owned.filter(id=>SHARKS.some(s=>s.id===id))])],selected:v.owned.includes(v.selected)?v.selected:'reef',best:Number.isFinite(v.best)?v.best:0,runs:Array.isArray(v.runs)?v.runs.filter(x=>typeof x==='string').slice(-40):[]}}
try{let raw=localStorage.getItem(KEY);if(raw)save=validSave(JSON.parse(raw));else save.best=Number(localStorage.getItem('sharkline-best'))||0}catch(e){memoryOnly=true;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save))}catch{memoryOnly=true;toast('Sauvegarde indisponible : garde cette fenêtre ouverte.')}}
function refreshSave(){if(memoryOnly)return;try{const raw=localStorage.getItem(KEY);if(raw)save=validSave(JSON.parse(raw))}catch{}}
let selectedZone='reef',detailId='reef',mode='port',run=null,runId='',paid=false,view='play',last=0,pointer=null,keys=new Set(),boostHeld=false,toastTimer;
const canvas=$('ocean'),ctx=canvas.getContext('2d'),images={};let W=innerWidth,H=innerHeight,dpr=1;
for(const s of SHARKS){const im=new Image();im.src='./'+s.id+'.svg';images[s.id]=im;}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4200)}
function shark(){return SHARKS.find(s=>s.id===save.selected)||SHARKS[0]}
function renderPort(){const s=shark();$('wallet').textContent=save.coins.toLocaleString('fr-FR');$('selectedName').textContent=s.name;$('selectedArt').src='./'+s.id+'.svg';$('selectedArt').alt=s.name;$('selectedRole').textContent=s.filter?'Filtreur de plancton':s.skillName;$('ownedCount').textContent=save.owned.length+' / 20 requins acquis · Cartes documentaires accessibles à tous';$('zones').replaceChildren();for(const z of zones){const b=document.createElement('button');b.className='zone'+(selectedZone===z.id?' active':'');b.setAttribute('aria-pressed',selectedZone===z.id);b.innerHTML='<span class="zoneIcon">'+z.icon+'</span><b>'+z.name+'</b><small>'+z.description+'</small>';b.onclick=()=>{selectedZone=z.id;renderPort()};$('zones').append(b)}$('missionList').innerHTML=(s.filter?['Collecter 80 planctons','Collecter 25 pièces','Explorer 3 balises']:['Capturer 30 proies','Collecter 25 pièces','Explorer 3 balises']).map(t=>'<li>'+t+'</li>').join('');renderCards();}
function renderCards(){const filter=$('filter').value;$('cards').replaceChildren();for(const s of SHARKS){const owned=save.owned.includes(s.id);if(filter==='owned'&&!owned||filter==='shop'&&owned)continue;const card=document.createElement('article');card.className='card'+(save.selected===s.id?' selected':'');card.innerHTML='<div class="cardArtwork"><span class="tag">'+(save.selected===s.id?'ÉQUIPÉ':owned?'ACQUIS':s.status==='EX'?'BONUS FOSSILE':'À DÉBLOQUER')+'</span><img src="./'+s.id+'.svg" alt="Silhouette de '+s.name+'" loading="lazy"></div><div class="cardBody"><h3>'+s.name+'</h3><p>'+s.skillName+'</p><div class="miniStats"><span>Vitesse<b>'+s.speed+' m/s</b></span><span>Taille jeu<b>'+s.length+' m</b></span></div></div>';const body=card.querySelector('.cardBody'),details=document.createElement('button');details.className='textButton';details.textContent='Carte & documentaire';details.onclick=()=>openDetail(s.id);body.append(details);const action=document.createElement('button');action.className=owned?'secondary':'primary';action.textContent=save.selected===s.id?'Équipé':owned?'Équiper':'◉ '+s.price.toLocaleString('fr-FR');action.disabled=save.selected===s.id;action.onclick=()=>owned?equip(s.id):openDetail(s.id);body.append(action);$('cards').append(card)}}
function equip(id){refreshSave();if(!save.owned.includes(id))return;save.selected=id;persist();renderPort();if($('detail').open)renderDetail();toast('Requin équipé : '+shark().name)}
function buy(id){refreshSave();const s=SHARKS.find(s=>s.id===id);if(!s||save.owned.includes(id))return;if(save.coins<s.price){toast('Il te manque '+(s.price-save.coins)+' pièces. Pars en expédition !');renderDetail();return}save.coins-=s.price;save.owned.push(id);save.selected=id;persist();renderPort();renderDetail();toast(s.name+' acheté et équipé !')}
function setView(v){view=v;$('lobby').hidden=v!=='play';$('collection').hidden=v!=='collection';$('tabPlay').classList.toggle('active',v==='play');$('tabCollection').classList.toggle('active',v==='collection');window.scrollTo(0,0)}
$('tabPlay').onclick=()=>setView('play');$('tabCollection').onclick=()=>setView('collection');$('filter').onchange=renderCards;$('selectedDetails').onclick=()=>openDetail(save.selected);
function openDetail(id){detailId=id;renderDetail();setDetailTab(false);$('detail').showModal()}
function setDetailTab(doc){$('statsPane').hidden=doc;$('docPane').hidden=!doc;$('statTab').classList.toggle('active',!doc);$('docTab').classList.toggle('active',doc)}
$('closeDetail').onclick=()=>$('detail').close();$('statTab').onclick=()=>setDetailTab(false);$('docTab').onclick=()=>setDetailTab(true);
function renderDetail(){const s=SHARKS.find(s=>s.id===detailId),owned=save.owned.includes(s.id);$('detailTop').innerHTML='<div><h2>'+s.name+'</h2><p>'+s.scientific+'</p></div><img src="./'+s.id+'.svg" alt="'+s.name+'">';const stats=[['Vitesse',s.speed,'m/s · croisière'],['Accélération',s.accel,'s · 0 → croisière'],['Taille',s.length,'m · longueur du jeu'],['Endurance',s.endurance,'s · boost continu'],['Vitalité',s.hp,'points'],['Puissance',s.damage,'dégâts / morsure'],['Maniabilité',s.agility,'sur 100'],['Boost',(s.speed*1.8).toFixed(1),'m/s · maximum']];$('statsPane').innerHTML='<p class="note">Valeurs de jeu, choisies pour l’équilibrage. Elles ne sont pas des mesures biologiques.</p><div class="statsGrid">'+stats.map(([label,val,unit])=>'<div class="stat"><small>'+label+'</small><b>'+val+'</b><em>'+unit+'</em></div>').join('')+'</div><div class="ability"><strong>'+s.skillName+'</strong><p>'+s.skillText+'</p><p>Recharge : '+s.cooldown+' secondes.</p></div>'+(s.filter?'<p class="note">Mode pacifique : collecte du plancton, aucune morsure. Même récompense de mission que les chasseurs.</p>':'<p class="note">Morsure automatique lorsque le museau touche une proie. La croissance pendant la partie a été retirée.</p>');
const fields=[['Répartition',s.range],['Habitat',s.habitat],['Taille réelle',s.realSize],['Alimentation',s.diet],['Mode de vie',s.life],['Reproduction',s.reproduction],['Population mondiale',s.population],['Tendance',s.trend]];const points=s.points.map(([lon,lat])=>'<i style="left:'+((lon+180)/360*100)+'%;top:'+((90-lat)/180*100)+'%"></i>').join('');$('docPane').innerHTML='<div class="documentary"><div class="docField full"><h3>Conservation · '+s.status+'</h3><p>'+statuses[s.status]+'</p><p class="note">'+(s.status==='EX'?'Espèce disparue, présente uniquement comme bonus fictif.':'Statut mondial UICN relayé par FishBase (édition 2025-2). Évaluation : '+s.assessment+'.')+'</p></div><div class="docField full"><h3>Repères géographiques</h3><div class="map" aria-label="Quelques repères géographiques, consulter le texte pour la répartition"><img src="./world.svg" alt="Planisphère schématique">'+points+'</div><p class="note">Points indicatifs '+(s.status==='EX'?'de régions fossilifères':'de présence')+' ; ce schéma ne délimite pas l’aire de répartition.</p></div>'+fields.map(([label,t])=>'<div class="docField"><h3>'+label+'</h3><p>'+t+'</p></div>').join('')+'<div class="docField full"><h3>Le savais-tu ?</h3><p>'+s.fact+'</p></div></div><div class="sources">Sources consultées le 01/10/2026 · Les connaissances et évaluations évoluent.<br><a href="'+s.source+'" target="_blank" rel="noopener">'+(s.status==='EX'?'Smithsonian Ocean':'Florida Museum')+'</a><a href="'+s.statusSource+'" target="_blank" rel="noopener">'+(s.status==='EX'?'Fiche paléontologique':'FishBase / référence UICN')+'</a></div>';$('detailAction').replaceChildren();const action=document.createElement('button');action.className='primary';action.textContent=save.selected===s.id?'Requin équipé':owned?'Équiper ce requin':'Acheter · '+s.price.toLocaleString('fr-FR')+' pièces';action.disabled=save.selected===s.id||(!owned&&save.coins<s.price);action.onclick=()=>owned?equip(s.id):buy(s.id);$('detailAction').append(action);if(!owned&&save.coins<s.price){const p=document.createElement('p');p.className='note';p.textContent='Il te manque '+(s.price-save.coins)+' pièces.';$('detailAction').append(p)}}
function clearControls(){pointer=null;keys.clear();boostHeld=false;$('knob').style.transform='translate(0,0)';$('boost').classList.remove('pressed')}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function launch(){refreshSave();run=new Expedition(shark(),selectedZone);runId=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);paid=false;mode='play';clearControls();$('harbor').hidden=true;$('gameScreen').hidden=false;document.body.classList.add('playing');$('result').close();resize();updateHud()}
$('launch').onclick=launch;$('again').onclick=launch;
function pause(){if(mode!=='play')return;mode='pause';clearControls();$('pauseDialog').showModal()}
function resume(){if(mode!=='pause')return;$('pauseDialog').close();mode='play';clearControls()}
$('pause').onclick=pause;$('resume').onclick=resume;$('pauseDialog').addEventListener('cancel',e=>{e.preventDefault();resume()});$('quit').onclick=()=>{$('pauseDialog').close();run.end(false);complete()};
function complete(){if(paid||!run)return;paid=true;mode='end';clearControls();refreshSave();const r=run.reward();if(!save.runs.includes(runId)){save.coins+=r.total;save.best=Math.max(save.best,r.total);save.runs.push(runId);save.runs=save.runs.slice(-40);persist()}$('resultLabel').textContent=run.won?'MISSION · RETOUR À LA SURFACE':run.hp<=0?'EXPÉDITION INTERROMPUE':'RETOUR AU PORT';$('resultTitle').textContent=run.won?'Bien joué.':'Tes gains sont conservés.';$('resultBody').innerHTML='<div class="resultAmount">+'+r.total+' ◉</div><div class="resultLines">Pièces ramassées<span>'+r.collection+'</span><br>'+(run.shark.filter?'Plancton':'Chasse')+'<span>'+r.hunting+'</span><br>Temps de survie<span>'+r.survival+'</span><br>Objectifs ('+run.missionsDone()+'/3)<span>'+r.missions+'</span><br>Survie complète<span>'+r.completion+'</span></div><p class="note">'+Math.floor(run.time)+' s · '+run.food+' '+(run.shark.filter?'planctons':'proies')+' · '+run.visited.size+' balises<br>Solde : '+save.coins+' pièces</p>';$('result').showModal();renderPort()}
function returnPort(v){$('result').close();mode='port';clearControls();$('gameScreen').hidden=true;$('harbor').hidden=false;document.body.classList.remove('playing');renderPort();setView(v)}$('toShop').onclick=()=>returnPort('collection');$('toLobby').onclick=()=>returnPort('play');$('result').addEventListener('cancel',e=>{e.preventDefault();returnPort('play')});
canvas.addEventListener('pointerdown',e=>{if(mode!=='play'||e.clientX>W*.65||pointer)return;canvas.setPointerCapture(e.pointerId);pointer={id:e.pointerId,ox:e.clientX,oy:e.clientY,x:0,y:0}});canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;let dx=e.clientX-pointer.ox,dy=e.clientY-pointer.oy;const n=Math.hypot(dx,dy),r=45;if(n>r){dx*=r/n;dy*=r/n}pointer.x=dx/r;pointer.y=dy/r;$('knob').style.transform='translate('+dx*.75+'px,'+dy*.75+'px)'});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(pointer&&pointer.id===e.pointerId){pointer=null;$('knob').style.transform='translate(0,0)'}});
$('boost').addEventListener('pointerdown',e=>{if(mode!=='play')return;e.preventDefault();$('boost').setPointerCapture(e.pointerId);boostHeld=true;$('boost').classList.add('pressed')});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('boost').addEventListener(event,()=>{boostHeld=false;$('boost').classList.remove('pressed')});$('special').onclick=()=>{if(mode==='play')run.useSkill()};
addEventListener('keydown',e=>{if(mode!=='play'&&mode!=='pause')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='Escape'){e.preventDefault();if(mode==='play')pause();else resume();return}if(mode!=='play')return;keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e'&&!e.repeat)run.useSkill()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});addEventListener('storage',e=>{if(e.key===KEY){refreshSave();if(mode==='port')renderPort()}});
function input(){let x=pointer?.x||0,y=pointer?.y||0;if(keys.has('arrowleft')||keys.has('q')||keys.has('a'))x=-1;if(keys.has('arrowright')||keys.has('d'))x=1;if(keys.has('arrowup')||keys.has('z')||keys.has('w'))y=-1;if(keys.has('arrowdown')||keys.has('s'))y=1;return{x,y,boost:boostHeld||keys.has(' ')}}
function updateHud(){if(!run)return;$('zoneName').textContent=zones.find(z=>z.id===run.zone).name.toUpperCase();let t=Math.ceil(180-run.time);$('timer').textContent=Math.floor(t/60)+':'+String(t%60).padStart(2,'0');$('hp').max=run.shark.hp;$('hp').value=Math.max(0,run.hp);$('hpText').textContent=Math.ceil(Math.max(0,run.hp))+'/'+run.shark.hp;$('energy').value=run.energy;$('runCoins').textContent='◉ '+run.reward().total;$('special').disabled=run.cooldown>0;$('specialStatus').textContent=run.cooldown>0?Math.ceil(run.cooldown)+' s':'PRÊT';$('alert').textContent=run.messageTime>0?run.message:'';$('objectives').innerHTML=run.objectives.map(o=>'<span class="'+(run.value(o)>=o.target?'done':'')+'">'+(o.type==='food'?(run.shark.filter?'Plancton ':'Proies '):o.type==='coins'?'Pièces ':'Balises ')+Math.min(run.value(o),o.target)+'/'+o.target+(run.value(o)>=o.target?' ✓':'')+'</span>').join('')}
function path(points,fill,stroke){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function creature(img,x,y,len,face=1,a=0,alpha=1){if(!img?.complete||!img.naturalWidth)return;ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.scale(face,1);ctx.globalAlpha=alpha;ctx.drawImage(img,-len/2,-len*.2,len,len*.4);ctx.restore()}
function fishArt(o,t){ctx.save();ctx.translate(o.x,o.y);ctx.scale(o.dir,1);const colors=['#8fcacc','#ecc88c','#cf9baa','#c2d8a7'];ctx.fillStyle=colors[o.variant];ctx.beginPath();ctx.ellipse(0,0,16+o.variant*3,7+o.variant,0,0,7);ctx.fill();path([[-13,0],[-24,-9],[-23,9]],colors[o.variant]);path([[-2,-5],[4,-14],[9,-5]],colors[o.variant]);ctx.fillStyle='#152f3f';ctx.beginPath();ctx.arc(9, -1,2,0,7);ctx.fill();ctx.restore()}
function jelly(o,t){ctx.save();ctx.translate(o.x,o.y);ctx.strokeStyle='#da9fdf99';ctx.lineWidth=2;for(let j=0;j<4;j++){ctx.beginPath();ctx.moveTo(-12+j*8,5);ctx.bezierCurveTo(-10+j*8+Math.sin(t*2+j)*8,17,-16+j*8,28,-10+j*8,37);ctx.stroke()}ctx.fillStyle='#cc98cdcc';ctx.beginPath();ctx.arc(0,0,18,Math.PI,Math.PI*2);ctx.lineTo(18,6);ctx.quadraticCurveTo(0,13,-18,6);ctx.closePath();ctx.fill();ctx.fillStyle='#f5d6ed';ctx.beginPath();ctx.ellipse(-5,-6,4,2,-.5,0,7);ctx.fill();ctx.restore()}
function orca(o,t){ctx.save();ctx.translate(o.x,o.y);ctx.scale(o.x<run.x?1:-1,1);ctx.fillStyle='#172831';ctx.beginPath();ctx.ellipse(0,0,85,26,0,0,7);ctx.fill();path([[-65,0],[-115,-30],[-98,0],[-115,25]],'#172831');path([[-15,-15],[-1,-82],[18,-20]],'#172831');ctx.fillStyle='#d7e9e8';ctx.beginPath();ctx.ellipse(13,12,56,11,.04,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(46,-6,14,6,-.1,0,7);ctx.fill();ctx.fillStyle='#07121b';ctx.beginPath();ctx.arc(64,-7,3,0,7);ctx.fill();ctx.restore()}
function scenery(cx,cy,z,t){ctx.save();ctx.translate(-cx*.3,-cy*.2);ctx.globalAlpha=.25;for(let i=0;i<16;i++){const x=i*730;path([[x,1600],[x+120,900+(i%3)*90],[x+410,1200],[x+550,800+(i%4)*100],[x+760,1600]],run.zone==='reef'?'#26616a':'#1d3e58')}ctx.restore();ctx.save();ctx.translate(-cx,-cy);
ctx.strokeStyle='#a3e8e84a';ctx.lineWidth=2;ctx.beginPath();for(let x=Math.floor(cx/50)*50;x<cx+W/z+50;x+=20){let y=105+Math.sin(x*.02+t)*4;x===Math.floor(cx/50)*50?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke();ctx.fillStyle='#102e3e';ctx.fillRect(0,1335,run.width,200);
for(let i=Math.max(0,Math.floor(cx/330)-1);i<Math.min(29,Math.ceil((cx+W/z)/330)+1);i++){const x=i*330;path([[x-30,1340],[x+20,1290],[x+95,1260+(i%3)*20],[x+170,1310],[x+250,1340]],'#24434a');if(run.zone==='reef'){ctx.lineCap='round';ctx.strokeStyle=i%2?'#aa7670':'#698a8a';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(x+70,1320);ctx.lineTo(x+70,1250);ctx.moveTo(x+70,1280);ctx.lineTo(x+43,1255);ctx.moveTo(x+70,1268);ctx.lineTo(x+94,1238);ctx.stroke();ctx.strokeStyle='#487e67';ctx.lineWidth=5;for(let a=0;a<4;a++){ctx.beginPath();ctx.moveTo(x+190+a*10,1335);ctx.quadraticCurveTo(x+175+a*10+Math.sin(t+a)*10,1280,x+180+a*12,1210+a*10);ctx.stroke()}}else if(run.zone==='abyss'){path([[x+40,1340],[x+50,1210],[x+75,1220],[x+95,1340]],'#263943');ctx.fillStyle='#72ceca22';ctx.beginPath();ctx.ellipse(x+62,1170,27,75,0,0,7);ctx.fill()}}
if(run.zone==='wreck'){const x=2850,y=1200;ctx.save();ctx.translate(x,y);ctx.rotate(.12);path([[-450,0],[350,0],[410,-70],[-430,-100]],'#374c50','#799092');ctx.fillStyle='#374c50';ctx.fillRect(-150,-220,260,130);ctx.fillRect(-60,-280,90,60);ctx.fillStyle='#0b2937';for(let i=0;i<7;i++){ctx.fillRect(-340+i*90,-60,40,28)}for(let i=0;i<4;i++)ctx.fillRect(-122+i*52,-182,30,28);ctx.strokeStyle='#728888';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-240,-85);ctx.lineTo(-245,-450);ctx.lineTo(70,-390);ctx.stroke();ctx.restore()}
for(const n of run.nets){ctx.strokeStyle='#beb89b88';ctx.lineWidth=1;for(let yy=n.y;yy<n.y+n.h;yy+=18){ctx.beginPath();ctx.moveTo(n.x,yy);ctx.lineTo(n.x+n.w,yy+12);ctx.stroke()}for(let xx=n.x;xx<=n.x+n.w;xx+=8){ctx.beginPath();ctx.moveTo(xx,n.y);ctx.lineTo(xx,n.y+n.h);ctx.stroke()}ctx.strokeStyle='#ded0a9';ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.lineTo(n.x,n.y+n.h);ctx.stroke()}
for(let i=0;i<run.beacons.length;i++){const b=run.beacons[i],done=run.visited.has(i);ctx.save();ctx.translate(b.x,b.y);ctx.fillStyle=done?'#74e3c1':'#f4d388';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=20;path([[0,-16],[10,0],[0,16],[-10,0]],ctx.fillStyle);ctx.shadowBlur=0;ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(done?'EXPLORÉE':'BALISE '+(i+1),0,35);ctx.restore()}
ctx.restore();}
function render(t){if(!run)return;const z=W<600?Math.min(.78,H/1400):1,cx=Math.max(0,Math.min(run.width-W/z,run.x-W/z*.44)),cy=Math.max(0,Math.min(run.height-H/z,run.y-H/z*.46));ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,run.zone==='reef'?'#176279':run.zone==='wreck'?'#174659':'#081c37');g.addColorStop(1,run.zone==='reef'?'#052733':'#031824');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
if(run.zone!=='abyss'){ctx.save();ctx.globalAlpha=.055;for(let i=0;i<6;i++){path([[i*W/5-90,0],[i*W/5-30,0],[i*W/5+220,H],[i*W/5+50,H]],'#cff6ff')}ctx.restore()}
ctx.save();ctx.scale(z,z);scenery(cx,cy,z,t);ctx.translate(-cx,-cy);for(const o of run.objects){if(!o.alive||o.x<cx-180||o.x>cx+W/z+180||o.y<cy-100||o.y>cy+H/z+100)continue;if(o.type==='fish')fishArt(o,t);else if(o.type==='coin'){ctx.fillStyle='#f4d388';ctx.beginPath();ctx.ellipse(o.x,o.y,6+Math.abs(Math.sin(t*2+o.phase))*3,10,0,0,7);ctx.fill();ctx.strokeStyle='#98793a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(o.x,o.y-4);ctx.lineTo(o.x,o.y+4);ctx.stroke()}else if(o.type==='plankton'){ctx.fillStyle='#9ff0cf';ctx.shadowColor='#74e3c1';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(o.x,o.y,3.5,0,7);ctx.fill();ctx.shadowBlur=0}else if(o.type==='jelly')jelly(o,t);else if(o.type==='enemy')creature(images.white,o.x,o.y,130,o.x<run.x?1:-1);else if(o.type==='orca')orca(o,t)}
if(run.active>0){ctx.strokeStyle=run.shark.skill==='shield'?'#91e9d5aa':'#e6d88d66';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(run.x,run.y,run.baseLength*.65,run.baseLength*.35,0,0,7);ctx.stroke()}
creature(images[run.shark.id],run.x,run.y,run.baseLength,run.face,run.angle,run.invuln>0?.6+Math.sin(t*25)*.3:1);if(run.time<6){ctx.fillStyle='#c9eee6';ctx.font='11px Arial';ctx.textAlign='center';ctx.fillText('TON REQUIN',run.x,run.y-36);}for(const p of run.pops){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.font='bold 15px Arial';ctx.textAlign='center';ctx.fillText(p.text,p.x,p.y-25-(1-p.life)*40)}ctx.globalAlpha=1;ctx.restore();
if(run.zone==='abyss'){ctx.save();const x=(run.x-cx)*z,y=(run.y-cy)*z;const shade=ctx.createRadialGradient(x,y,70,x,y,Math.max(W,H)*.7);shade.addColorStop(0,'#010b1800');shade.addColorStop(.55,'#010b1866');shade.addColorStop(1,'#010b18c0');ctx.fillStyle=shade;ctx.fillRect(0,0,W,H);ctx.restore()}
for(let i=0;i<18;i++){let x=(i*157-cx*.25)%W;if(x<0)x+=W;let y=H-((t*13+i*97)%H);ctx.strokeStyle='#c2e6ef25';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,1.5+i%3,0,7);ctx.stroke()}
if(run.active>0&&run.shark.skill==='radar'){for(const o of run.objects){if(!o.alive||!['fish','enemy','orca'].includes(o.type)||Math.hypot(o.x-run.x,o.y-run.y)>1000)continue;const px=(o.x-cx)*z,py=(o.y-cy)*z;if(px>30&&px<W-30&&py>130&&py<H-130)continue;ctx.fillStyle=o.type==='fish'?'#74e3c1':'#ff9792';ctx.beginPath();ctx.arc(Math.max(25,Math.min(W-25,px)),Math.max(140,Math.min(H-145,py)),5,0,7);ctx.fill()}}
ctx.fillStyle='#8eb4c1';ctx.font='11px Arial';ctx.textAlign='right';ctx.fillText('PROFONDEUR JEU '+Math.round((run.y-120)*.12)+' m',W-18,H-165);
}
let hudTick=0;function frame(ms){let dt=Math.min(.05,Math.max(0,(ms-last)/1000||0));last=ms;if(mode==='play'){run.step(dt,input());hudTick+=dt;if(hudTick>.12){updateHud();hudTick=0}if(run.ended){updateHud();complete()}}if(run&&mode!=='port')render(ms/1000);requestAnimationFrame(frame)}renderPort();if(memoryOnly)setTimeout(()=>toast('Sauvegarde indisponible : progression conservée pour cette session seulement.'),500);requestAnimationFrame(frame);
