'use strict';
(function(root){
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class Expedition{
 constructor(shark,zone,rng=Math.random){this.shark=shark;this.zone=zone;this.rng=rng;this.width=9000;this.height=1400;this.time=0;this.duration=180;this.hp=shark.hp;this.energy=100;this.x=700;this.y=600;this.vx=0;this.vy=0;this.face=1;this.angle=0;this.food=0;this.coins=0;this.attackCD=0;this.invuln=0;this.cooldown=0;this.active=0;this.ended=false;this.won=false;this.visited=new Set();this.objects=[];this.pops=[];this.messages=[];this.orcaClock=0;this.messageTime=0;this.skillUses=0;this.baseLength=clamp(110+shark.length*15,125,270);this.objectives=shark.filter?[{type:'food',label:'Filtrer 80 planctons',target:80},{type:'coins',label:'Collecter 25 pièces',target:25},{type:'explore',label:'Explorer 3 balises',target:3}]:[{type:'food',label:'Capturer 30 proies',target:30},{type:'coins',label:'Collecter 25 pièces',target:25},{type:'explore',label:'Explorer 3 balises',target:3}];this.beacons=[{x:1350,y:760},{x:3300,y:1000},{x:5800,y:500}];for(let i=0;i<155;i++)this.objects.push(this.spawn('fish'));for(let i=0;i<160;i++)this.objects.push(this.spawn('plankton'));for(let i=0;i<75;i++)this.objects.push(this.spawn('coin'));for(let i=0;i<22;i++)this.objects.push(this.spawn('jelly'));for(let i=0;i<7;i++)this.objects.push(this.spawn('enemy'));for(let i=0;i<8;i++){const o=this.spawn(shark.filter?'plankton':'fish');o.x=this.rand(500,1300);o.y=this.rand(400,950);o.hp=15;this.objects.push(o)}for(let i=0;i<10;i++){const o=this.spawn('coin');o.x=this.rand(600,1700);o.y=this.rand(450,1000);this.objects.push(o)}this.nets=zone==='wreck'?[{x:2400,y:400,w:25,h:230},{x:4200,y:750,w:30,h:260}]:zone==='abyss'?[{x:4700,y:650,w:28,h:280}]:[{x:3800,y:250,w:25,h:190}];this.tell(shark.filter?'Filtre le plancton lumineux. Les poissons restent indemnes.':'Chasse les poissons. Mange pour récupérer de la vitalité.');}
 rand(a,b){return a+this.rng()*(b-a)}
 spawn(type,near=false){let x=near?clamp(this.x+this.rand(-800,1000),80,this.width-80):this.rand(80,this.width-80),y=near?clamp(this.y+this.rand(-400,400),160,1250):this.rand(160,1250);return{type,x,y,dir:this.rng()<.5?-1:1,speed:type==='enemy'?110:this.rand(20,65),phase:this.rand(0,7),hp:type==='enemy'?130:type==='fish'?this.rand(12,55):1,variant:Math.floor(this.rand(0,4)),stun:0,alive:true};}
 tell(text){this.message=text;this.messageTime=4;}
 pop(x,y,text,color='#74e3c1'){this.pops.push({x,y,text,color,life:1});}
 useSkill(){if(this.ended||this.cooldown>0)return false;this.skillUses++;this.cooldown=this.shark.cooldown;this.active=this.shark.skill==='radar'?6:4;if(this.shark.skill==='heal')this.hp=Math.min(this.shark.hp,this.hp+25);if(this.shark.skill==='endurance')this.energy=100;if(this.shark.skill==='stun')for(const o of this.objects)if(Math.hypot(o.x-this.x,o.y-this.y)<320)o.stun=4;this.tell(this.shark.skillName+' activé');return true;}
 value(objective){return objective.type==='food'?this.food:objective.type==='coins'?this.coins:this.visited.size;}
 missionsDone(){return this.objectives.filter(o=>this.value(o)>=o.target).length;}
 reward(){const collection=this.coins*3;const hunting=Math.min(120,this.food*(this.shark.filter?1:2));const survival=Math.floor(this.time/3);const missions=this.missionsDone()*80;const completion=this.won?150:0;return{collection,hunting,survival,missions,completion,total:collection+hunting+survival+missions+completion};}
 end(won=false){if(this.ended)return;this.ended=true;this.won=won;this.hp=Math.max(0,this.hp);}
 damage(amount){if(this.invuln>0||this.ended)return;this.hp-=amount*(this.active>0&&this.shark.skill==='shield'?.5:1);this.invuln=1.2;this.pop(this.x,this.y,'−'+Math.round(amount),'#ff9792');}
 step(delta,input={x:0,y:0,boost:false}){
 if(this.ended)return;const dt=clamp(delta,0,.05);this.time=Math.min(this.duration,this.time+dt);this.cooldown=Math.max(0,this.cooldown-dt);this.active=Math.max(0,this.active-dt);this.invuln=Math.max(0,this.invuln-dt);this.attackCD=Math.max(0,this.attackCD-dt);this.messageTime=Math.max(0,this.messageTime-dt);const oldDone=this.missionsDone();let ix=clamp(Number(input.x)||0,-1,1),iy=clamp(Number(input.y)||0,-1,1);const norm=Math.hypot(ix,iy);if(norm>1){ix/=norm;iy/=norm}const sprint=!!input.boost&&this.energy>1&&norm>.1;const specialSpeed=this.active>0&&this.shark.skill==='dash'?1.35:1;const maxSpeed=this.shark.speed*25*(sprint?1.8:1)*specialSpeed;const reversing=(this.vx*ix<0||this.vy*iy<0);const accel=this.shark.speed*25/this.shark.accel*(reversing?(.45+this.shark.agility/100):1);const tx=ix*maxSpeed,ty=iy*maxSpeed;this.vx+=clamp(tx-this.vx,-accel*dt,accel*dt);this.vy+=clamp(ty-this.vy,-accel*dt,accel*dt);this.x=clamp(this.x+this.vx*dt,this.baseLength/2+15,this.width-this.baseLength/2-15);this.y=clamp(this.y+this.vy*dt,150,this.height-110);if(Math.abs(this.vx)>8)this.face=this.vx<0?-1:1;const desired=clamp(Math.atan2(this.vy,Math.abs(this.vx)+30),-.55,.55)*this.face;this.angle+=(desired-this.angle)*Math.min(1,dt*(3+this.shark.agility/10));this.energy=clamp(this.energy+(sprint?-100/this.shark.endurance:15)*dt,0,100);this.hp-=dt*(this.shark.filter?.28:.48);if(this.zone==='abyss')this.hp-=dt*.06;
 const noseX=this.x+this.face*this.baseLength*.35,noseY=this.y;let biteRadius=this.baseLength*.23+15;if(this.active>0&&this.shark.skill==='ambush')biteRadius*=2;let filterRadius=this.baseLength*.35+20;if(this.active>0&&this.shark.skill==='filter')filterRadius*=2;
 for(const o of this.objects){if(!o.alive)continue;const dist=Math.hypot(o.x-this.x,o.y-this.y);if(dist>1500)continue;o.stun=Math.max(0,o.stun-dt);if(o.stun<=0){if(o.type==='fish'){const flee=!this.shark.filter&&dist<145;o.x+=(flee?(o.x<this.x?-1:1)*70:o.dir*o.speed)*dt;o.y+=Math.sin(this.time*.9+o.phase)*5*dt;}else if(o.type==='enemy'||o.type==='orca'){let hunt=dist<(o.type==='orca'?950:400);o.x+=(hunt?Math.sign(this.x-o.x):o.dir)*(o.type==='orca'?135:o.speed)*dt;if(hunt)o.y+=Math.sign(this.y-o.y)*65*dt;}else if(o.type==='jelly'){o.y+=Math.sin(this.time+o.phase)*9*dt;}if(o.x<40||o.x>this.width-40){o.dir*=-1;o.x=clamp(o.x,40,this.width-40)}}
 if(o.type==='coin'&&dist<this.baseLength*.42+16){this.coins++;this.pop(o.x,o.y,'+3 ◉','#f4d388');o.alive=false;}
 if(o.type==='plankton'&&this.shark.filter&&Math.hypot(o.x-noseX,o.y-noseY)<filterRadius){this.food++;this.hp=Math.min(this.shark.hp,this.hp+1.8);o.alive=false;}
 if((o.type==='fish'||o.type==='enemy')&&!this.shark.filter&&Math.hypot(o.x-noseX,o.y-noseY)<biteRadius&&this.attackCD===0){o.hp-=this.shark.damage*(this.active>0&&this.shark.skill==='power'?2:1);this.attackCD=.3;if(o.hp<=0){o.alive=false;this.food++;this.hp=Math.min(this.shark.hp,this.hp+(o.type==='enemy'?24:9));this.pop(o.x,o.y,'+1 proie');}else this.pop(o.x,o.y,'Morsure');}
 if(o.type==='jelly'&&dist<this.baseLength*.32+23)this.damage(16);if((o.type==='enemy'||o.type==='orca')&&o.alive&&dist<this.baseLength*.35+(o.type==='orca'?70:38)){this.damage(o.type==='orca'?40:22);if(o.type==='orca')this.tell('ORQUE · Accélère pour t’échapper !');}}
 for(const n of this.nets)if(this.x+this.baseLength*.35>n.x&&this.x-this.baseLength*.35<n.x+n.w&&this.y>n.y-20&&this.y<n.y+n.h+20){this.damage(15);this.vx*=.97;this.tell('FILET · Contourne-le par le haut ou le bas.');}
 for(let i=0;i<this.beacons.length;i++){const b=this.beacons[i];if(!this.visited.has(i)&&Math.hypot(b.x-this.x,b.y-this.y)<120){this.visited.add(i);this.pop(b.x,b.y,'Balise explorée','#f4d388');this.tell('Balise '+this.visited.size+'/3 explorée');}}
 if(this.missionsDone()>oldDone)this.tell('Objectif accompli · +80 pièces au retour !');this.orcaClock+=dt;if(this.orcaClock>48){this.orcaClock=0;const o=this.spawn('orca',true);o.x=clamp(this.x+900,100,this.width-100);o.y=this.y;o.hp=9999;this.objects.push(o);this.tell('Une orque approche. Reste en mouvement !');}
 this.pops=this.pops.filter(p=>(p.life-=dt)>0);if(Math.floor(this.time*10)%80===0&&this.rng()<.08){for(let i=0;i<6;i++)this.objects.push(this.spawn(this.shark.filter?'plankton':'fish',true));}if(this.objects.length>550)this.objects=this.objects.filter(o=>o.alive||o.type==='orca');if(this.hp<=0)this.end(false);else if(this.time>=this.duration)this.end(true);
 }
}
root.Expedition=Expedition;
})(typeof window!=='undefined'?window:globalThis);
