'use strict';
const $=id=>document.getElementById(id), canvas=$('ocean'),ctx=canvas.getContext('2d');
const specs=[{name:'Bleu',unlock:0,speed:170,growth:1,drain:1,desc:'Équilibré · Un excellent premier chasseur.'},{name:'Mako',unlock:600,speed:215,growth:.95,drain:1.1,desc:'Vitesse +25 % · Idéal pour semer les prédateurs.'},{name:'Marteau',unlock:1600,speed:175,growth:1,drain:.9,desc:'Radar · Les dangers hors écran sont signalés.'},{name:'Tigre',unlock:3200,speed:160,growth:1.25,drain:1,desc:'Croissance +25 % · Grandis plus vite en chassant.'},{name:'Grand blanc',unlock:5500,speed:145,growth:1,drain:1.2,desc:'Puissance · Commence à 1,6 m et récupère plus de vitalité.'}];
let best=0;try{best=Number(localStorage.getItem('sharkline-best'))||0}catch{}let selected=0,mode='menu',W=0,H=0,dpr=1,last=0,elapsed=0,score=0,eaten=0,health=100,energy=100,size=1,angle=0,invuln=0,eventClock=0,noticeTimer=0,boost=false,player={x:1400,y:1400},fish=[],particles=[],pointer=null,keys=new Set();
const world=2800,icons=['🐟','🐠','🐡','🦑','🦐','🦀','🐟','🐠','🐟','🐠','🦑','🐡','🐟','🐠','🦐','🦀','🐟','🐠','🦑','🐟'];
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function choose(i){selected=i;drawSelection()}
function drawSelection(){$('record').textContent='RECORD '+best;$('sharks').replaceChildren();specs.forEach((s,i)=>{const b=document.createElement('button');b.className=i===selected?'active':'';b.disabled=best<s.unlock;b.setAttribute('aria-pressed',i===selected);b.innerHTML='<b>'+(b.disabled?'🔒':'🦈')+'</b>'+s.name;b.title=b.disabled?'Record de '+s.unlock+' points requis':s.desc;b.onclick=()=>choose(i);$('sharks').append(b)});$('ability').textContent=specs[selected].desc}
function spawn(initial=false,kind){let x,y;if(initial){x=rand(40,world-40);y=rand(40,world-40)}else{let a=rand(0,Math.PI*2),r=Math.max(W,H)*.65+rand(100,250);x=clamp(player.x+Math.cos(a)*r,40,world-40);y=clamp(player.y+Math.sin(a)*r,40,world-40)}const k=kind??Math.floor(rand(0,20));let s=.3+k*.075;let predator=k>=17;if(predator)s=k===19?5.5:2.4+(k-17)*.8;return{x,y,s,kind:k,icon:predator?(k===19?'🐋':'🦈'):icons[k],a:rand(0,Math.PI*2),turn:rand(0,5),speed:predator?95:rand(35,80)}}
function setMode(m){mode=m;for(const [id,on]of Object.entries({menu:m==='menu',hud:['play','pause'].includes(m),pause:['play','pause'].includes(m),boost:m==='play',hint:m==='play',result:m==='end',paused:m==='pause',footer:m==='menu'}))$(id).hidden=!on;pointer=null;boost=false;keys.clear();$('boost').classList.remove('pressed')}
function start(){elapsed=score=eaten=invuln=eventClock=0;health=energy=100;size=selected===4?1.6:1;angle=-Math.PI/2;player={x:1400,y:1400};fish=Array.from({length:170},()=>spawn(true));for(let i=0;i<18;i++){const a=rand(0,7),r=rand(80,350);const f=spawn(true,Math.floor(rand(0,7)));f.x=player.x+Math.cos(a)*r;f.y=player.y+Math.sin(a)*r;fish.push(f)}particles=[];setMode('play');tell('Mange les proies vertes. Évite les rouges.',4);updateHud()}
function tell(text,seconds=3){$('notice').textContent=text;noticeTimer=seconds}
function finish(won){let old=best;best=Math.max(best,score);try{localStorage.setItem('sharkline-best',String(best))}catch{}setMode('end');$('endLabel').textContent=won?'TROIS MINUTES DANS LE GRAND BLEU':'L’OCÉAN A EU LE DERNIER MOT';$('endTitle').textContent=won?'Survivant.':'Fin de la chasse.';$('finalScore').textContent=score;$('finalEaten').textContent=eaten;$('finalSize').textContent=size.toFixed(1)+' m';let unlocked=specs.filter(s=>s.unlock>old&&s.unlock<=best).map(s=>s.name);$('newRecord').textContent=unlocked.length?'Nouveau requin : '+unlocked.join(', '):score>old?'Nouveau record !':'Record sur cet appareil : '+best;$('notice').textContent='';drawSelection()}
function pause(){if(mode==='play')setMode('pause');else if(mode==='pause')setMode('play')}
$('play').onclick=start;$('replay').onclick=start;$('back').onclick=()=>setMode('menu');$('pause').onclick=pause;$('resume').onclick=pause;$('quit').onclick=()=>{setMode('menu');$('notice').textContent=''};
canvas.addEventListener('pointerdown',e=>{if(mode!=='play')return;canvas.setPointerCapture(e.pointerId);pointer={x:e.clientX,y:e.clientY,id:e.pointerId}});canvas.addEventListener('pointermove',e=>{if(pointer&&e.pointerId===pointer.id){pointer.x=e.clientX;pointer.y=e.clientY}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(ev,()=>pointer=null);
$('boost').addEventListener('pointerdown',e=>{if(mode!=='play')return;e.preventDefault();$('boost').setPointerCapture(e.pointerId);boost=true;$('boost').classList.add('pressed')});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('boost').addEventListener(ev,()=>{boost=false;$('boost').classList.remove('pressed')});addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='Escape'){pause();return}keys.add(e.key.toLowerCase())});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')setMode('pause')});addEventListener('blur',()=>{if(mode==='play')setMode('pause')});
function updateHud(){$('score').textContent=score;$('size').textContent=size.toFixed(1)+' m';const t=Math.ceil(Math.max(0,180-elapsed));$('time').textContent=Math.floor(t/60)+':'+String(t%60).padStart(2,'0');$('health').value=health;$('energy').value=energy}
function step(dt){elapsed+=dt;invuln=Math.max(0,invuln-dt);noticeTimer-=dt;if(noticeTimer<=0)$('notice').textContent='';let dx=0,dy=0;if(pointer){dx=pointer.x-W/2;dy=pointer.y-H/2}if(keys.has('arrowup')||keys.has('z')||keys.has('w'))dy=-100;if(keys.has('arrowdown')||keys.has('s'))dy=100;if(keys.has('arrowleft')||keys.has('q')||keys.has('a'))dx=-100;if(keys.has('arrowright')||keys.has('d'))dx=100;let moving=Math.hypot(dx,dy)>12;if(moving)angle=Math.atan2(dy,dx);let sprint=(boost||keys.has(' '))&&energy>2&&moving;energy=clamp(energy+(sprint?-30:18)*dt,0,100);let speed=specs[selected].speed*(sprint?1.9:1)*(moving?1:.32);player.x=clamp(player.x+Math.cos(angle)*speed*dt,25,world-25);player.y=clamp(player.y+Math.sin(angle)*speed*dt,25,world-25);health-=dt*(.95+size*.12)*specs[selected].drain;const radius=18+size*7;
for(let i=0;i<fish.length;i++){let f=fish[i],dist=Math.hypot(f.x-player.x,f.y-player.y);f.turn-=dt;if(f.s>size&&f.kind>=17&&dist<340)f.a=Math.atan2(player.y-f.y,player.x-f.x);else if(f.s<size*.95&&dist<130)f.a=Math.atan2(f.y-player.y,f.x-player.x);else if(f.turn<0){f.a+=rand(-1,1);f.turn=rand(1,4)}f.x+=Math.cos(f.a)*f.speed*dt;f.y+=Math.sin(f.a)*f.speed*dt;if(f.x<20||f.x>world-20){f.a=Math.PI-f.a;f.x=clamp(f.x,20,world-20)}if(f.y<20||f.y>world-20){f.a=-f.a;f.y=clamp(f.y,20,world-20)}if(dist<radius+10+f.s*4){if(f.s<=size*.95){let value=Math.round(20+f.s*45);score+=value;eaten++;health=clamp(health+7+f.s*4+(selected===4?3:0),0,100);let prev=Math.floor(size);size=Math.min(6,size+(.024+f.s*.025)*specs[selected].growth);particles.push({x:f.x,y:f.y,text:'+'+value,life:1,color:'#61eec6'});fish[i]=spawn(false);if(Math.floor(size)>prev)tell('Tu grandis ! De nouvelles proies sont accessibles.')}else if(invuln<=0){health-=f.s>size*1.25?30:15;invuln=1.4;particles.push({x:player.x,y:player.y,text:'DANGER',life:1,color:'#fa7c85'});const a=Math.atan2(player.y-f.y,player.x-f.x);player.x=clamp(player.x+Math.cos(a)*60,25,world-25);player.y=clamp(player.y+Math.sin(a)*60,25,world-25)}}}
eventClock+=dt;if(eventClock>32){eventClock=0;tell('Migration de sardines · Le festin approche !',4);for(let i=0;i<18;i++){let f=spawn(false,0);f.x=clamp(player.x+rand(-280,280),40,world-40);f.y=clamp(player.y+rand(-280,280),40,world-40);fish.push(f)}if(fish.length>250)fish.splice(0,18)}particles=particles.filter(p=>(p.life-=dt)>0);updateHud();if(health<=0)finish(false);else if(elapsed>=180)finish(true)}
function sprite(icon,x,y,r,a,alpha=1){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.globalAlpha=alpha;ctx.font=(r*2)+'px "Apple Color Emoji","Segoe UI Emoji",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.scale(-1,1);ctx.fillText(icon,0,0);ctx.restore()}
function render(t){ctx.clearRect(0,0,W,H);let bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,'#062d3b');bg.addColorStop(.5,'#073743');bg.addColorStop(1,'#031924');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);let active=['play','pause','end'].includes(mode),camx=active?player.x-W/2:900,camy=active?player.y-H/2:1000;ctx.save();ctx.translate(-camx,-camy);ctx.strokeStyle='#39778414';ctx.lineWidth=1;for(let x=0;x<=world;x+=140){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,world);ctx.stroke()}for(let y=0;y<=world;y+=140){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(world,y);ctx.stroke()}for(let i=0;i<100;i++){let x=(i*391.7)%world,y=(i*673.1)%world;ctx.fillStyle=i%3?'#28758418':'#42c4ad12';ctx.beginPath();ctx.arc(x,y,15+(i%5)*15,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#76e0d5';ctx.lineWidth=5;ctx.strokeRect(0,0,world,world);
if(active){for(const f of fish){let sx=f.x-camx,sy=f.y-camy;if(sx<-100||sy<-100||sx>W+100||sy>H+100){if(selected===2&&f.kind>=17&&f.s>size&&Math.hypot(f.x-player.x,f.y-player.y)<650){let a=Math.atan2(f.y-player.y,f.x-player.x),r=Math.min(W,H)*.42;ctx.fillStyle='#fa7c85';ctx.beginPath();ctx.arc(player.x+Math.cos(a)*r,player.y+Math.sin(a)*r,5,0,7);ctx.fill()}continue}let color=f.s<=size*.95?'#61eec6':f.s>size*1.25?'#fa7c85':'#ffc66c';let r=12+f.s*7;ctx.strokeStyle=color+'55';ctx.lineWidth=1;ctx.beginPath();ctx.arc(f.x,f.y,r+4,0,7);ctx.stroke();sprite(f.icon,f.x,f.y,r,f.a);ctx.fillStyle=color;ctx.beginPath();ctx.arc(f.x,f.y-r-9,3,0,7);ctx.fill()}
ctx.shadowColor='#6ae8d2';ctx.shadowBlur=25;sprite('🦈',player.x,player.y,18+size*7,angle,invuln>0?.5+Math.sin(t*25)*.25:1);ctx.shadowBlur=0;for(const p of particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.font='bold 17px Arial';ctx.textAlign='center';ctx.fillText(p.text,p.x,p.y-(1-p.life)*50)}ctx.globalAlpha=1;if(pointer){ctx.strokeStyle='#79e4d744';ctx.lineWidth=2;ctx.beginPath();ctx.arc(pointer.x+camx,pointer.y+camy,25,0,7);ctx.stroke()}}
else{for(let i=0;i<14;i++){let x=camx+W*.65+Math.sin(t*.2+i)*W*.2,y=camy+((i*89+t*13)%(H+100))-50;sprite(i%4?'🐟':'🐠',x,y,12+i%3*5,.2,.25)}sprite('🦈',camx+W*.75,camy+H*.5+Math.sin(t*.7)*20,Math.min(110,W*.13),-.28,.9)}ctx.restore();let shade=ctx.createLinearGradient(0,0,W,0);shade.addColorStop(0,active?'#02182000':'#021820ef');shade.addColorStop(1,'#02182000');ctx.fillStyle=shade;ctx.fillRect(0,0,W,H);for(let i=0;i<25;i++){let x=(i*137.3)%W,y=H-((t*15+i*83)%H);ctx.strokeStyle='#8cd8dd22';ctx.beginPath();ctx.arc(x,y,1+i%3,0,7);ctx.stroke()}}
function frame(ms){const dt=Math.min(.04,(ms-last)/1000||0);last=ms;if(mode==='play')step(dt);render(ms/1000);requestAnimationFrame(frame)}drawSelection();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_game_state',description:'Lire le score, le requin et l’état de la partie.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode,shark:specs[selected].name,score,best,size,remaining:Math.ceil(180-elapsed)})})}catch{}}
