'use strict';
window.isLevelUnlocked=id=>{for(let i=1;i<id;i++)if(!(save.campaign.levels[i]>0))return false;return id>=1&&id<=9};
function renderCampaign(){const levels=save.campaign.levels,total=Object.values(levels).reduce((a,n)=>a+n,0),done=LEVELS.filter(l=>levels[l.id]>0).length;$('campaignProgress').textContent=done+'/9 niveaux réussis · '+total+'/27 étoiles · Requin équipé : '+shark().name;$('levelGroups').replaceChildren();for(const z of zones){const group=document.createElement('section');group.className='levelGroup';const title=document.createElement('h2');title.textContent=z.name;group.append(title);const grid=document.createElement('div');grid.className='levelGrid';for(const l of LEVELS.filter(l=>l.zone===z.id)){const unlocked=window.isLevelUnlocked(l.id),stars=levels[l.id]||0,card=document.createElement('article');card.className='levelCard'+(unlocked?'':' locked')+(l.type==='boss'?' bossCard':'');card.innerHTML='<div class="levelNumber">'+String(l.id).padStart(2,'0')+' <span>'+(l.type==='boss'?'BOSS':'NIVEAU')+'</span></div><h3>'+l.title+'</h3><p>'+l.goal+'</p><p class="levelStars">'+'★'.repeat(stars)+'☆'.repeat(3-stars)+'</p><p class="note">'+l.duration+' s maximum · '+l.bonus+'</p>';const btn=document.createElement('button');btn.className='primary';btn.disabled=!unlocked;btn.textContent=!unlocked?'Termine le niveau précédent':stars?'Rejouer':'Plonger';btn.onclick=()=>window.launchCampaign(l.id);card.append(btn);grid.append(card)}group.append(grid);$('levelGroups').append(group)}}
$('tabCampaign').onclick=()=>setView('campaign');$('tabQuiz').onclick=()=>setView('quiz');$('campaignEquip').onclick=()=>setView('collection');$('nextLevel').onclick=()=>window.launchCampaign(run.level.id+1);$('toCampaign').onclick=()=>returnPort('campaign');
window.updateCampaignHud=()=>{const b=run?.boss;$('bossHud').hidden=!(b?.active);if(!b?.active)return;$('bossTitle').textContent=b.name;$('bossProgress').value=b.cleared?3:b.dodges;$('bossHint').textContent=b.cleared?'Passage ouvert : rejoins la sortie':b.phase==='warning'?(b.type==='trawl'?'Rejoins l’ouverture verte':'Charge annoncée : quitte la ligne rouge'):b.phase==='charge'?'Esquive !':b.type==='guardian'?'Repos : tu peux aussi mordre':'Souffle un instant';};
window.drawCampaign=t=>{if(!run?.level)return;const exit=run.level.exit;ctx.save();ctx.strokeStyle=run.prerequisites()?'#74e3c1':'#d9c48d';ctx.lineWidth=5;ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(exit,250);ctx.lineTo(exit,1180);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=ctx.strokeStyle;ctx.font='bold 17px Arial';ctx.textAlign='center';ctx.fillText('SORTIE',exit,220);const b=run.boss;if(b?.active&&!b.cleared){if(b.type==='trawl'){const x=b.phase==='warning'?b.startX:b.x;ctx.fillStyle=b.phase==='warning'?'#f4d38822':'#b39a7699';ctx.fillRect(x-12,150,24,Math.max(0,b.gapY-200-150));ctx.fillRect(x-12,b.gapY+200,24,1400-b.gapY-200);ctx.strokeStyle='#efd1a699';ctx.lineWidth=1;for(let yy=150;yy<1300;yy+=24){if(yy>b.gapY-200&&yy<b.gapY+200)continue;ctx.beginPath();ctx.moveTo(x-12,yy);ctx.lineTo(x+12,yy+20);ctx.stroke();}ctx.strokeStyle='#74e3c1';ctx.lineWidth=4;ctx.strokeRect(x-25,b.gapY-200,50,400);if(b.phase==='warning'){ctx.fillStyle='#74e3c1';ctx.font='bold 16px Arial';ctx.fillText('OUVERTURE',Math.min(run.x+200,x-70),b.gapY);}}
else{if(b.phase==='warning'){ctx.fillStyle='#ff77772a';ctx.fillRect(Math.max(0,run.x-900),b.targetY-60,1800,120);ctx.strokeStyle='#ff9e8a';ctx.lineWidth=2;ctx.setLineDash([15,10]);ctx.beginPath();ctx.moveTo(Math.max(0,run.x-900),b.targetY);ctx.lineTo(Math.min(run.width,run.x+900),b.targetY);ctx.stroke();ctx.setLineDash([]);}if(b.type==='guardian'){creature(images.greatHammer,b.x,b.y,280,-1);if(b.phase==='rest'){ctx.fillStyle='#f4d388';ctx.font='12px Arial';ctx.fillText('REPOS',b.x,b.y-65);}}else orca({x:b.x,y:b.y},t);}}ctx.restore()};
let quizMode='discovery',quizRun=null,quizTimerHandle=null,pendingImport=null;
function localDay(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function renderQuizIntro(){const day=localDay();const earned=save.quiz.day===day?save.quiz.earned:0;$('quizRecord').textContent='Meilleur résultat : '+save.quiz.best+'/5 · Pièces de quiz aujourd’hui : '+earned+'/100';}
window.onPortRefresh=()=>{renderCampaign();renderQuizIntro();};window.onPortRefresh();
function setQuizMode(m){quizMode=m;$('quizDiscovery').classList.toggle('active',m==='discovery');$('quizChallenge').classList.toggle('active',m==='challenge');$('quizDiscovery').setAttribute('aria-pressed',m==='discovery');$('quizChallenge').setAttribute('aria-pressed',m==='challenge')}
$('quizDiscovery').onclick=()=>setQuizMode('discovery');$('quizChallenge').onclick=()=>setQuizMode('challenge');
function stopQuizClock(){clearInterval(quizTimerHandle);quizTimerHandle=null}
function startQuiz(){refreshSave();stopQuizClock();quizRun={questions:makeQuiz(save.quiz.mistakes,save.quiz.recent),index:0,correct:0,answered:false,remaining:20,finished:false,mode:quizMode,mistakes:{}};$('quizIntro').hidden=true;$('quizResult').hidden=true;$('quizSession').hidden=false;showQuestion()}
function showQuestion(){stopQuizClock();const q=quizRun.questions[quizRun.index];quizRun.answered=false;quizRun.remaining=20;$('quizCount').textContent='QUESTION '+(quizRun.index+1)+' / 5';$('quizCategory').textContent=q.kind;$('quizQuestion').textContent=q.prompt;$('quizTimer').textContent=quizRun.mode==='challenge'?'20 s':'Sans chrono';$('quizOptions').replaceChildren();$('quizFeedback').hidden=true;$('nextQuestion').hidden=true;$('nextQuestion').textContent=quizRun.index===4?'Voir mon résultat':'Question suivante';for(const id of q.options){const s=SHARKS.find(s=>s.id===id),btn=document.createElement('button');btn.className='quizOption';btn.dataset.answer=id;btn.textContent=s.name;btn.onclick=()=>answerQuiz(id);$('quizOptions').append(btn)}if(quizRun.mode==='challenge')quizTimerHandle=setInterval(()=>{if(document.hidden||view!=='quiz'||quizRun.answered)return;quizRun.remaining--;$('quizTimer').textContent=quizRun.remaining+' s';if(quizRun.remaining<=0)answerQuiz(null)},1000)}
function answerQuiz(id){if(!quizRun||quizRun.answered||quizRun.finished)return;quizRun.answered=true;stopQuizClock();const q=quizRun.questions[quizRun.index],correct=id===q.correct;if(correct)quizRun.correct++;quizRun.mistakes[q.id]=correct?-1:1;for(const b of $('quizOptions').children){b.disabled=true;b.classList.toggle('correct',b.dataset.answer===q.correct);b.classList.toggle('incorrect',b.dataset.answer===id&&!correct)}$('quizFeedback').hidden=false;$('quizFeedback').innerHTML='<strong>'+(correct?'Bonne réponse !':id===null?'Temps écoulé.':'À retenir pour la prochaine fois.')+'</strong><p>'+q.explanation+'</p><button id="quizSpecies" class="textButton">Découvrir cette espèce</button><a href="'+q.source+'" target="_blank" rel="noopener">Source documentaire</a>';$('quizSpecies').onclick=()=>openDetail(q.shark);$('nextQuestion').hidden=false;}
function finishQuiz(){if(!quizRun||quizRun.finished)return;quizRun.finished=true;stopQuizClock();refreshSave();const day=localDay();if(save.quiz.day!==day){save.quiz.day=day;save.quiz.earned=0}const earned=Math.min(quizRun.correct*10,100-save.quiz.earned);save.quiz.earned+=earned;save.coins+=earned;save.quiz.best=Math.max(save.quiz.best,quizRun.correct);save.quiz.recent=quizRun.questions.map(q=>q.id);for(const [id,change]of Object.entries(quizRun.mistakes))save.quiz.mistakes[id]=Math.min(20,Math.max(0,(save.quiz.mistakes[id]||0)+change));persist();renderPort();$('quizSession').hidden=true;$('quizResult').hidden=false;$('quizResultTitle').textContent=quizRun.correct+' / 5 bonnes réponses';$('quizResultText').textContent='+'+earned+' pièces · '+(earned===0&&save.quiz.earned===100?'La limite quotidienne est atteinte. Tu peux continuer à apprendre.':'Les questions ratées reviendront plus souvent.');}
$('startQuiz').onclick=startQuiz;$('quizAgain').onclick=startQuiz;$('nextQuestion').onclick=()=>{if(!quizRun?.answered)return;if(quizRun.index===4)finishQuiz();else{quizRun.index++;showQuestion()}};$('quitQuiz').onclick=()=>{stopQuizClock();quizRun=null;$('quizSession').hidden=true;$('quizResult').hidden=true;$('quizIntro').hidden=false;toast('Session quittée. Les pièces sont attribuées après les 5 questions.');};
function downloadJSON(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
$('exportSave').onclick=()=>{refreshSave();downloadJSON('SHARKLINE-sauvegarde-'+localDay()+'.json',{format:'sharkline-save',edition:4,date:new Date().toISOString(),data:validSave(save)});toast('Copie exportée. Garde le fichier JSON pour restaurer ta progression.');};
$('importSave').onclick=()=>$('saveFile').click();$('saveFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>300000)throw Error('Fichier trop volumineux');const parsed=JSON.parse(await f.text());if(parsed.format&&parsed.format!=='sharkline-save')throw Error('Format de sauvegarde inconnu');pendingImport=validSave(parsed.data||parsed);$('importSummary').textContent=pendingImport.coins+' pièces · '+pendingImport.owned.length+' requins · '+Object.values(pendingImport.campaign.levels).reduce((a,b)=>a+b,0)+' étoiles';$('importDialog').showModal();}catch(error){pendingImport=null;toast('Import refusé : '+error.message)}};
$('confirmImport').onclick=()=>{if(!pendingImport)return;save=pendingImport;pendingImport=null;persist();$('importDialog').close();renderPort();toast('Progression restaurée.');};$('cancelImport').onclick=()=>{pendingImport=null;$('importDialog').close()};$('importDialog').addEventListener('cancel',()=>pendingImport=null);
